ALTER TABLE "Post"
  ADD COLUMN "weekdays" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],
  ADD COLUMN "seasons" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "arrivalTime" VARCHAR(5),
  ADD COLUMN "departureTime" VARCHAR(5);
ALTER TABLE "Post" DROP COLUMN "place", DROP COLUMN "endDate", DROP COLUMN "endTime", DROP COLUMN "endsAt";
